#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=InstallTEA
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:15:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd $HOME/tea-main/

# Optional: remove any old env first
conda env remove --name tea --yes || true

# Create the env from the .yml
conda env create -f tea_env.yml

